### PR TITLE
Accessibility and keyboard navigation issues

### LINKED ISSUE #34: Accessibility and keyboard navigation issues
Keyboard navigation and accessibility in general have a few issues. Namely the sponsor's slider. Creating this issue to hopefully work on some fixes.

### PR DESCRIPTION
**Pull request by mackenly**
Accessibility and keyboard navigation fixes

Closes #34

### CODE REVIEW

**Review by RyannosaurusRex — APPROVED** [review]
Thanks! Looks good!

**Comment by RyannosaurusRex** [comment]
Are you using [aXe ](https://www.deque.com/axe/)for scanning for these or something else?

**Comment by mackenly** [comment]
@RyannosaurusRex No, just chrome dev tools. I'll check that out though.

**Comment by RyannosaurusRex** [comment]
@mackenly Hey, this is still in Draft it looks like. Just wanted to follow up on it and make sure it wasn't actually ready you were waiting on me. 😅

**Comment by mackenly** [comment]
> @mackenly Hey, this is still in Draft it looks like. Just wanted to follow up on it and make sure it wasn't actually ready you were waiting on me. 😅 

Ah, oops. I think it's okay as is but more improvements could be made.

**Comment by mackenly** [comment]
Closing since v2 will completely redesign

**Pull request closed without merging**
