### PR TITLE
18 the matrix easter egg

### PR DESCRIPTION
**Pull request by fudgemasterultra**
Adding in matrix effect easter egg.
Have event listener on window that captures key presses.  if at some point "neo" is typed in it will start the matrix. Had to add global css because they aren't in place on the jsx until the classes are needed later on, and svelte trying to save me from myself would get rid of that unused css for me.

### CODE REVIEW

**Comment by mackenly** [comment]
Should standardize the backgrounds? The logo is currently a JPG (no transparency), so we could convert it to a transparent PNG or to an SVG. Alternatively, we could set the background color of the links to black and not let the matrix show through. 

I personally like the look of the matrix effect showing through, but I think both the logo and buttons should match. That's of course a stylistic opinion and probably needs discussion.

image

**Comment by fudgemasterultra** [comment]
I wonder if @jeffrainey has a svg logo with a transparent background?

**Comment by jeffrainey** [comment]
@fudgemasterultra @mackenly Good call! I will get this in later tonight. I can commit it into this branch.

**Comment by RyannosaurusRex** [comment]
After looking at the preview, I personally kinda like the buttons and logo solid. Kings makes it pop a little more. Personal preference, though.

**Comment by fudgemasterultra** [comment]
So I made it run a little faster, and I think it looks pretty nice now. So before I merge it in. Are we going no transparent, or not? Luckily it really isn't that big of a deal, because most people will never see it.

**Comment by RyannosaurusRex** [comment]
@fudgemasterultra Went to merge this but has some conflicts in the imports. Can you fix those up and then I'll merge it in. Thanks!

**Pull request merged**
